import { Button } from '@/components/ui/button';
import { FloatingParticles } from '@/components/Quiz/FloatingParticles';
import { Header } from '@/components/Layout/Header';
import { useNavigate } from 'react-router-dom';
import { Sparkles, Brain, Zap, TrendingUp } from 'lucide-react';

const Home = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen relative">
      <FloatingParticles />
      <Header />
      
      <main className="container mx-auto px-4 pt-32 pb-16 relative z-10">
        {/* Hero Section */}
        <div className="text-center mb-20 animate-fade-in">
          <div className="inline-block mb-6">
            <div className="w-24 h-24 mx-auto rounded-2xl bg-gradient-to-br from-primary via-secondary to-accent flex items-center justify-center animate-pulse-glow">
              <Sparkles className="w-12 h-12 text-white" />
            </div>
          </div>
          
          <h1 className="text-5xl md:text-7xl font-bold mb-6 glow-text">
            Discover Your
            <br />
            <span className="bg-gradient-to-r from-primary via-secondary to-accent bg-clip-text text-transparent gradient-animate">
              IT Personality
            </span>
          </h1>
          
          <p className="text-xl md:text-2xl text-muted-foreground mb-8 max-w-2xl mx-auto">
            Take our interactive quiz and unlock personalized insights powered by AI
          </p>

          <Button
            size="lg"
            onClick={() => navigate('/quiz')}
            className="text-lg px-8 py-6 rounded-xl bg-gradient-to-r from-primary to-secondary hover:shadow-lg hover:shadow-primary/50 transition-all hover:scale-105"
          >
            <Sparkles className="w-5 h-5 mr-2" />
            Start the Quiz
          </Button>

          <p className="text-sm text-muted-foreground mt-4">
            Takes about 5 minutes • 12 engaging questions
          </p>
        </div>

        {/* Features */}
        <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto mb-20">
          <div className="glass-card p-8 rounded-2xl text-center group hover:bg-card/60 transition-all hover:scale-105">
            <div className="w-16 h-16 rounded-xl bg-primary/20 flex items-center justify-center mx-auto mb-4 group-hover:bg-primary/30 transition-colors">
              <Brain className="w-8 h-8 text-primary" />
            </div>
            <h3 className="text-xl font-bold mb-2">AI-Powered Analysis</h3>
            <p className="text-muted-foreground">
              Get personalized insights generated by advanced AI based on your unique responses
            </p>
          </div>

          <div className="glass-card p-8 rounded-2xl text-center group hover:bg-card/60 transition-all hover:scale-105">
            <div className="w-16 h-16 rounded-xl bg-secondary/20 flex items-center justify-center mx-auto mb-4 group-hover:bg-secondary/30 transition-colors">
              <Zap className="w-8 h-8 text-secondary" />
            </div>
            <h3 className="text-xl font-bold mb-2">Instant Results</h3>
            <p className="text-muted-foreground">
              Receive your complete personality profile immediately after completing the quiz
            </p>
          </div>

          <div className="glass-card p-8 rounded-2xl text-center group hover:bg-card/60 transition-all hover:scale-105">
            <div className="w-16 h-16 rounded-xl bg-accent/20 flex items-center justify-center mx-auto mb-4 group-hover:bg-accent/30 transition-colors">
              <TrendingUp className="w-8 h-8 text-accent" />
            </div>
            <h3 className="text-xl font-bold mb-2">Career Guidance</h3>
            <p className="text-muted-foreground">
              Discover ideal career paths and learning resources tailored to your strengths
            </p>
          </div>
        </div>

        {/* Stats */}
        <div className="glass-card p-8 rounded-2xl max-w-4xl mx-auto">
          <div className="grid md:grid-cols-3 gap-8 text-center">
            <div>
              <div className="text-4xl font-bold text-primary mb-2">10,000+</div>
              <div className="text-muted-foreground">IT Professionals</div>
            </div>
            <div>
              <div className="text-4xl font-bold text-secondary mb-2">10</div>
              <div className="text-muted-foreground">Personality Types</div>
            </div>
            <div>
              <div className="text-4xl font-bold text-accent mb-2">95%</div>
              <div className="text-muted-foreground">Accuracy Rate</div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;